set(_CATKIN_CURRENT_PACKAGE "topic_vscode_c")
set(topic_vscode_c_VERSION "0.0.0")
set(topic_vscode_c_MAINTAINER "lin <lin@todo.todo>")
set(topic_vscode_c_PACKAGE_FORMAT "2")
set(topic_vscode_c_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(topic_vscode_c_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(topic_vscode_c_BUILDTOOL_DEPENDS "catkin")
set(topic_vscode_c_BUILDTOOL_EXPORT_DEPENDS )
set(topic_vscode_c_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(topic_vscode_c_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(topic_vscode_c_TEST_DEPENDS )
set(topic_vscode_c_DOC_DEPENDS )
set(topic_vscode_c_URL_WEBSITE "")
set(topic_vscode_c_URL_BUGTRACKER "")
set(topic_vscode_c_URL_REPOSITORY "")
set(topic_vscode_c_DEPRECATED "")